# Generated by Django 4.0.5 on 2025-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
