# Generated by Django 4.0.5 on 2026-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_booking_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flightid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
